PedMp costumization
CocaColaBear/types-ragemp-c pull request #56
Opened 2020-02-25 12:43 UTC by ynhhoJ

2020-02-25 12:58 UTC, TheMysteriousVincent commented
Where is the changelog source for these changes?

2020-02-25 12:59 UTC, pixlcrashr requested changes

2020-02-25 12:59 UTC, TheMysteriousVincent commented on index.d.ts
> +	setHeadOverlay(overlayID: number, index: number, opacity: number);
Add explicit return type `void`.

2020-02-25 13:35 UTC, ynhhoJ commented
You can test it on RAGE MP.
For players works variant from wiki: https://wiki.rage.mp/index.php?title=Player::setHeadOverlay - ``player.setHeadOverlay(1, 4, 0.99, 1, 1);``

But if you try to use that on ped, this way doesn't work.

You need to use 3 arguments, like in native:
![image](https://user-images.githubusercontent.com/22500212/75251546-d9ba0780-57eb-11ea-98d7-878e5849a19a.png)
And then change color of element with ``setHeadOverlayColor``.
Idk why, but for ped costumization we need to use that way.

```js
// Doesn't work
mp.keys.bind(0x71, true, function() { // F2
    const ped = mp.peds.new(mp.game.joaat('mp_m_freemode_01'), mp.players.local.position, mp.players.local.getHeading(), mp.players.local.dimension);
    setTimeout(() => {
        ped.setHeadBlendData(1, 1, 0, 1, 1, 0, 1, 1, 0, false);
        ped.setHeadOverlay(1, 4, 0.99, 1, 1);
    }, 500);
});
```
```js
//works 
mp.keys.bind(0x71, true, function() { // F2
    const ped = mp.peds.new(mp.game.joaat('mp_m_freemode_01'), mp.players.local.position, mp.players.local.getHeading(), mp.players.local.dimension);
    setTimeout(() => {
        ped.setHeadBlendData(1, 1, 0, 1, 1, 0, 1, 1, 0, false);
        ped.setHeadOverlay(1, 4, 0.99);
        player.setHeadOverlayColor(1, 1, 1, 1);
    }, 500);
});
```

2020-02-25 13:39 UTC, TheMysteriousVincent commented
Good job so far but you are missing one method `setHeadBlendData`.

2020-02-25 13:40 UTC, TheMysteriousVincent commented
Btw. I only meant the official changelog for these API differences in version 1.0

2020-02-25 13:41 UTC, pixlcrashr approved these changes

2020-02-25 13:43 UTC, TheMysteriousVincent commented
Just to be sure: Are these changes related to the upcoming v. 1.0 or are these changes also valid for v. 0.3.7.2?

2020-02-25 13:45 UTC, ynhhoJ commented
Like i know, It should works in 0.3.7 in the same way. But we need to do some tests to be shure 100%

2020-02-25 14:57 UTC, TheMysteriousVincent commented
Please test it, since we would merge directly into master.

2020-02-25 14:58 UTC, pixlcrashr approved these changes

2020-02-26 11:32 UTC, ynhhoJ commented
Yep, it's also works in 0.3.7!

2020-02-26 13:57 UTC, merged